### ISSUE TITLE
discuss assumptions/expectations of client versioning

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-client-go#13]
https://github.com/vapor-ware/synse-client-go/pull/12#discussion_r255555605

In the above PR, I noticed a few places where version caching was being done. While that idea has been around for a while and in some degree makes sense and is a nice feature, I think we should discuss its usefulness here/the assumptions built in around it. I *think* that we may be able to simplify a bunch of that stuff, but I'd like to discuss and pick your brain first, @hoanhan101.

**Comment by hoanhan101** [comment]
The way version caching is being implemented at the moment works as follows. For every versioned request, checks if the version is set. If it is, meaning `apiVersion` is not empty, skip that. Else, make a request to the `/version` endpoint and cache it.

So based on how version caching is being done, I think it serves only one purpose: to make sure the version is non-empty all the time. However, here we assume that the version wouldn't change in the future. The version caching only knows one version info for the rest of its life the first time it gets called. It means that, when we already have a non-empty value of `apiVersion` after the first request, there is no need to call the caching function again for every versioned request since it wouldn't change anything anyway. Also, we now have different contractors to create clients with specific version, meaning that the `apiVersion` is non-empty at init, there is no need to call the caching function anymore. Though I might miss something here, I agree the version caching is not really necessary and could be removed.

**Comment by edaniszewski** [comment]
Yeah, I came to the same conclusion. Basically, the mechanism by which its done here is fine, but I think the assumptions around it have changed a bit to the point where dynamically setting the version only becomes useful if we can return a client interface which all versioned clients can implement. Since the v3 and v2 APIs are different, we couldn't really do that without having the interface either:
- support the union of all client capabilities (which means functions will exist on some clients that do nothing)
- support the intersection of all client capabilities (which means that we can have core stuff supported like test/version/read/write, etc), but that means the clients become limited

Even if we did one of the above, the request/response scheme for each client may be different, even for common capabilities, so it would overall just be a nightmare to maintain that interface.


I think that since we have the versioned client constructors, we're fine just not even doing the whole version caching thing, which I think should simplify things.
