### ISSUE TITLE
Should the client have a config to skip certificate check?

### ISSUE THREAD

**Issue by hoanhan101** [vapor-ware/synse-client-go#24]
At the moment, what we have for TLS config options are:
```go
// TLSOptions is the config options for TLS/SSL communication.
type TLSOptions struct {
	// CertFile and KeyFile are public/private key pair from a pair of files to
	// use when communicating with Synse Server.
	CertFile string `default:"-"`
	KeyFile  string `default:"-"`

	// Enabled specifies whethere tls is enabled.
	Enabled bool `default:"false"`

	// SkipVerify specifies whether the client can skip certificate checks.
	SkipVerify bool `default:"false"`
}
```

Even though `SkipVerify` should only be used for testing, I am not sure if it's a good idea to leave it exported/configurable like so. Also, linting doesn't like that either.

**Comment by edaniszewski** [comment]
I think it should be fine to keep in. We will need it for testing, but it could also be useful to anyone who may be using Synse Server in the future and doing some development with it and some custom certs. That use case is sorta narrow, but still possible. While having it set to false is a security concern (hence the lint error), it is sorta up to the configurer to set it correctly for their use case. 

One thing we could do is set the default value to `true`, so that if someone wants to use `SkipVerify`, they have to explicitly set it?

**Comment by hoanhan101** [comment]
I think it's better to have `SkipVerify` to be `false` by default so it's guaranteed to be safe in the first place. If someone wants to skip the check due to their use case as you mentioned above, they can explicitly set it in their own risk. I feel like this would be more intuitive. 

So I guess this is fine for now. I will go ahead to make some notes/comments on the `SkipVerify` flag to make it clearer.

**Comment by edaniszewski** [comment]
Yeah, you're totally right. My brain stopped working for a minute there and mixed that up entirely, my bad.
