### ISSUE TITLE
should there be separate clients for websocket v http

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-client-go#8]
In #3, its proposed that we could specify websocket v. http in a config option to the SynseClient.

A question I have is whether is make sense to do it this way, or if the semantics/usage of websockets are different enough from http to just make it its own client, e.g. related to #7 
* NewHTTPClient
* NewHTTPClientV3
* NewWebsocketClient
* NewWebsocketClientV3

I'm not sure which makes the most sense, but I imagine that with a bit of research and some experimentation, it should become evident quickly

**Comment by hoanhan101** [comment]
I have been digging around to find some sample use of websocket, and  a library to use and it seems like [gorilla/websocket](https://github.com/gorilla/websocket) has the best to offer. It's simply because there is no other options that are as good (8k stars vs hundreds stars).

Looking through its examples that involve with client works, namely [chat](https://github.com/gorilla/websocket/tree/master/examples/chat) and [echo](https://github.com/gorilla/websocket/tree/master/examples/echo), it looks like the semantics/usage are different enough from what've been doing with http (socket connection vs http request). I think having a separate client as you mentioned above would make more sense in this case.
